---
- name: ansible dev vm
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ultral.ansible_development
    - role: andrewrothstein.terraform
    #- role: christiangda.awscli
  handlers:
    - name: Restart docker.service
      systemd:
        name: docker.service
        state: restarted
        enabled: true
        daemon_reload: true
  post_tasks:
    - name: Install extra software
      package:
        name:
          - git
          - epel-release
        state: present
      retries: 30
      delay: 5
      register: result
      until: result is not failed
    - name: Set kernel parameters
      # https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
      sysctl:
        name: fs.inotify.max_user_watches
        value: 524288
        sysctl_file: /etc/sysctl.d/99-vscode.conf
    - name: Install linters
      yum:
        name:
          - ShellCheck.x86_64
      retries: 30
      delay: 5
      register: result
      until: result is not failed
    - name: Add vagrant user to the root group
      user:
        name: vagrant
        group: root
        append: true
    - name: Create docker config dir
      file:
        state: directory
        path: /etc/systemd/system/docker.service.d/
        mode: 0755
    - name: Override default exec command
      copy:
        content: |+
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd
          ExecStartPost=/usr/bin/chmod o+rw /var/run/docker.sock
        dest: /etc/systemd/system/docker.service.d/docker.conf
        mode: 0644
      notify: Restart docker.service
