---
galaxy_info:
  namespace: iac
  role_name: gitlab_runner
  author: Lev Goncharov <lev.goncharov@t-systems.com>
  description: Gitlab Runner install
  company: T Systems
  license: Apache
  min_ansible_version: "2.8"
  platforms:
    - name: 'Centos'
      versions:
        - '7'
        - '8'

  galaxy_tags:
    - 'gitlabrunner'
    - 'gitlab'
    - 'ci'
    - 'agent'
    - 'git'

dependencies: []
