---
# We create template for runner registration
- name: Create gitlab-runner config template
  ansible.builtin.template:
    owner: root
    group: root
    mode: 0400
    dest: "{{ gitlab_runner_config_template_path }}"
    src: config.toml
  register: gitlab_result_config_template
  notify: Restart gitlab-runner.service

# we run registration only if the runner is not presented in the config and the template has been changed
- name: Register gitlab-runner
  ansible.builtin.command: gitlab-runner register --non-interactive --tag-list "{{ gitlab_runner_tags }}"
  environment:
    CI_SERVER_URL: "{{ gitlab_runner_server_url }}"
    RUNNER_EXECUTOR: shell
    REGISTRATION_TOKEN: "{{ gitlab_runner_registration_token }}"
    TEMPLATE_CONFIG_FILE: "{{ gitlab_runner_config_template_path }}"
  when:
    - not gitlab_result_registred_executor.found
    - gitlab_result_config_template.changed
  changed_when: false
  notify: Restart gitlab-runner.service
