---
- name: install gitlab-runner
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ultral.ansible_docker_centos
    - role: gitlab_runner
  vars_prompt:
    - name: gitlab_runner_registration_token
      prompt: 'Enter registration token from gitlab.com'
      private: true
  vars:
    gitlab_runner_register: true
